eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
logging:
    level:
        org:
            springframework:
                cloud:
                    gateway: TRACE
        reactor:
            netty: INFO
server:
    port: 8080
spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: master
                  uri: http://localhost:8001/
                  predicates:
                      - Path=/master/**
                - id: assessment
                  uri: http://localhost:8002/
                  predicates:
                      - Path=/assessment/**
    output:
        ansi:
            enabled: ALWAYS
