eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 7999
spring:
  application:
    name: jwt
    version: 1.0.0
  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      idle-timeout: 5000
      max-lifetime: 10000
      maximum-pool-size: 10
      minimum-idle: 3
      schema: school
    initialization-mode: always
    password: mypassword
    platform: postgres
    url: jdbc:postgresql://localhost:5432/master
    username: myusername
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    show-sql: true
  output:
    ansi:
      enabled: ALWAYS
